
project:
  type: website

website:
   
  navbar:
    left:
      - href: index.qmd
        text: Predicting Tennis Match Outcomes Using The Bradley Terry Model
      - href: interactive_plots_BT.qmd
        text: Interactive Plots
      - href: anims_and_plots.qmd
        text: Animations & Static Plots
      - href: bt_report_1.pdf
        text: Full Report
    right:
      - icon: github
        href: https://github.com/Enda6000
  page-footer: "Enda Byard Shaughnessy & James Brennan"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


