
project:
  type: website
  resources:
    - "h2h.html"
website:
   site-url: "https://enda-byard-shaughnessy.github.io/Bradley_Terry_Model_Tennis"
  navbar:
    left:
      - href: index.qmd
        text: Predicting Tennis Match Outcomes Using The Bradley Terry Model
      - href: interactive_plots_BT.qmd
        text: Interactive Plots & Graphs
      - href: anims_and_plots.qmd
        text: Animations & Static Plots
      - href: bt_report_1.pdf
        text: Full Report
    right:
      - icon: github
        href: https://github.com/enda-byard-shaughnessy
      - icon: linkedin
        href: https://www.linkedin.com/in/enda-byard-shaughnessy
  page-footer: "Hamilton Trust Research Internship 2026, Trinity College Dublin"
      

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    
#to update github files use 
#git add .
#git commit -m "update files"
#git push

#to update webpage
#quarto publish gh-pages




